FROM golang:1.22.2-alpine as backend
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o grpc-main ./personal-assitant-server/grpc
RUN go build -o botapi-main ./personal-assitant-server/botAPI