version: '3.8'

services:
  postgres:
    image: shwme1nilrepeat/personal-assistant-postgres:latest
    environment:
      POSTGRES_DB: novaDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NNA2s*123
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: shwme1nilrepeat/personal-assistant-redis:latest
    ports:
      - "16379:6379"

  elasticsearch:
    image: shwme1nilrepeat/personal-assistant-elastic:latest
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  backend:
    image: shwme1nilrepeat/personal-assistant-backend:latest
    command: ./grpc-main
    environment:
      - DATABASE_URL=postgres://postgres:NNA2s*123@postgres:15432/novaDB?sslmode=disable
      - REDIS_URL=redis://redis:16379
      - ELASTIC_URL=http://elasticsearch:9200
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    ports:
      - "50051:50051"
    depends_on:
      - postgres
      - redis
      - elasticsearch

  bot:
    image: shwme1nilrepeat/personal-assistant-backend:latest
    command: ./botapi-main
    environment:
      - DATABASE_URL=postgres://postgres:NNA2s*123@postgres:15432/novaDB?sslmode=disable
      - REDIS_URL=redis://redis:16379
      - ELASTIC_URL=http://elasticsearch:9200
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
      - elasticsearch

  frontend:
    image: shwme1nilrepeat/personal-assistant-frontend:latest
    environment:
      - REACT_APP_GRPC_HOST=http://localhost:8080/grpc
    ports:
      - "8081:80"
    depends_on:
      - backend
      - gateway-envoy

  gateway-envoy:
    image: envoyproxy/envoy:v1.28.0
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - personal-assistant-grpc

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8082:8082"
    depends_on:
      - frontend
      - gateway-envoy

networks:
  personal-assistant-grpc:

volumes:
  postgres-data:
