version: '3'

services:
  postgres:
    image: shwme1nilrepeat/personal-assistant-postgres:latest
    environment:
      POSTGRES_DB: novaDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NNA2s*123
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: shwme1nilrepeat/personal-assistant-redis:latest
    ports:
      - "16379:6379"

  elasticsearch:
    image: shwme1nilrepeat/personal-assistant-elastic:latest
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  backend:
    image: shwme1nilrepeat/personal-assistant-backend:latest
    environment:
      - DATABASE_URL=postgres://postgres:NNA2s*123@postgres:15432/novaDB?sslmode=disable
      - REDIS_URL=redis://redis:16379
      - ELASTIC_URL=http://elasticsearch:9200
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    ports:
      - "50051:50051"
#      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - elasticsearch

  frontend:
    image: shwme1nilrepeat/personal-assistant-frontend:latest
    environment:
      - REACT_APP_GRPC_HOST=http://backend:8080
    ports:
      - "8081:80"  # Изменение внешнего порта на 8081
    depends_on:
      - backend
  gateway-envoy:
    image: shwme1nilrepeat/personal-assistant-envoy:latest
    ports:
      - "8080:8080"
    networks:
      - personal-assistant-grpc

networks:
  personal-assistant-grpc:

volumes:
  postgres-data:
