apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-assitant-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: personal-assitant-frontend
  template:
    metadata:
      labels:
        app: personal-assitant-frontend
    spec:
      containers:
        - name: personal-assitant-frontend
          image: personal-assitant-client:latest
          ports:
            - containerPort: 80