apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubernetes-pods
spec:
  selector:
    matchLabels:
      team: frontend
  namespaceSelector:
    any: true
  endpoints:
    - port: http-metrics
      interval: 30s